apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-app
  template:
    metadata:
      labels:
        app: pingpong-app
    spec:
      volumes:
        - name: shared-pv
          persistentVolumeClaim:
            claimName: shared-pvc
      containers:
        - name: pingpong-app
          image: hanhsant/pingpong-app:v1.1.11
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-pv
              mountPath: /usr/src/app/files