apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-string-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-string-app
  template:
    metadata:
      labels:
        app: random-string-app
    spec:
      volumes:
        - name: shared-pv
          persistentVolumeClaim:
            claimName: shared-pvc
      containers:
        - name: create-random-string
          image: hanhsant/create-random-string:v1.1.11
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-pv
              mountPath: /usr/src/app/files
        - name: read-random-string
          image: hanhsant/read-random-string:v1.1.11
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-pv
              mountPath: /usr/src/app/files
          
     